### ISSUE TITLE
Fix kerning

### ISSUE THREAD

**Issue by StefanPeev** [JapanYoshi/stampatello-faceto#1]
@JapanYoshi I attach source files in which I offer some changes in features.fea file (OpenType features). I took the kerning pairs from [Snide Hand](https://github.com/JapanYoshi/snide-hand) in inserted them in features.fea file for Stampatello Faceto. This operation I made in the UFO version of Stampatello Faceto then I saved this version as .SFD (FontForge) an .VFC (FontLab) files.
[StampatelloFaceto-Sources.zip](https://github.com/JapanYoshi/stampatello-faceto/files/13321649/StampatelloFaceto-Sources.zip)

**Comment by JapanYoshi** [comment]
Thanks for your help. I've exported [a version with your kerning fix](https://github.com/JapanYoshi/stampatello-faceto/blob/main/otf/StampatelloFacetoKern.otf).

**Comment by JapanYoshi** [comment]
What was broken, by the way? I couldn't find anything out of the ordinary.

**Comment by StefanPeev** [comment]
The feature DLIG was the reason for the mess.
